

Here is a comprehensive master guide compiling everything we have discussed about DeepEval. This is organized for quick scannability and direct implementation into your software architecture.
------------------------------
## 1. What is DeepEval?
DeepEval is an open-source evaluation framework ("Pytest for LLMs") used to measure and unit-test the quality of LLM outputs. It transitions subjective AI responses into objective, mathematical scores from 0.0 to 1.0 alongside detailed, human-readable text explanations for debugging. [1, 2, 3, 4] 
------------------------------
## 2. Core Features for Evaluation

* 14+ Pre-Built Metrics: Out-of-the-box support for specialized calculations including Faithfulness, Answer Relevance, Hallucination, Toxicity, and Bias. [5, 6, 7, 8] 
* G-Eval Framework: A highly customizable metric that lets you pass custom evaluation criteria and custom logic steps using an advanced LLM as a judge. [9, 10, 11] 
* Dual Execution Engines: Can be run programmatically (.measure()) for application logic or as a terminal unit-test (assert_test) for CI/CD pipelines.
* Synthetic Data Generation: Tools to auto-generate testing datasets based on your source documents. [12, 13] 

------------------------------
## 3. How It Works (The Step-by-Step Mechanism)
DeepEval operates on an advanced LLM-As-A-Judge workflow combined with natural language processing algorithms: [14] 

   1. Extraction: DeepEval passes your AI output to a background judge model (like GPT-4o) and isolates the response into distinct, standalone factual statements. [15, 16] 
   2. Cross-Examination: It runs an automated prompt comparing each isolated statement against your source material or rules to check for contradictions.
   3. Mathematical Scoring: It applies a strict formula to determine the grade:
   $$\text{Score} = \frac{\text{Number of Verified Statements}}{\text{Total Number of Extracted Statements}}$$ [17] 
   4. Reason Compilation: It catches any failures during verification and outputs a text-based string (metric.reason) explaining exactly why points were deducted.

------------------------------
## 4. Required Parameters (The LLMTestCase)
DeepEval requires you to pack your data into an LLMTestCase object. The exact parameters needed depend on the metric you choose: [18] 

* input (String): The prompt sent by the user. (Required for Relevance, G-Eval).
* actual_output (String): The text response generated by your AI. (Required for all metrics).
* retrieval_context (List of Strings): The raw text reference segments your system used to form the answer. (Required for Faithfulness/Hallucination).
* expected_output (String): The ideal "perfect answer" or gold standard data. (Optional, used for exact accuracy metrics). [19, 20, 21, 22] 

------------------------------
## 5. How to Integrate DeepEval into a Validation Loop
Instead of blocking execution via console prints, you run the programmatic engine inside a while loop. If the score fails your threshold, you feed metric.reason back to your AI to fix itself.

from deepeval.test_case import LLMTestCasefrom deepeval.metrics import AnswerRelevanceMetric
# 1. Initialize metric programmaticallymetric = AnswerRelevanceMetric(threshold=0.8)attempts, max_retries = 0, 3ai_feedback = ""
while attempts < max_retries:
    attempts += 1
    
    # 2. Add feedback to prompt if it's a retry attempt
    prompt = "Your prompt here" + (f"\nFix based on: {ai_feedback}" if ai_feedback else "")
    actual_output = call_your_llm(prompt) 
    
    # 3. Create case and measure silently
    test_case = LLMTestCase(input="User Query", actual_output=actual_output)
    metric.measure(test_case)
    
    # 4. Check results to pass or loop back
    if metric.is_successful():
        print("✅ Validation Passed!")
        break
    else:
        ai_feedback = metric.reason # Catch the reason to fix the next loop

------------------------------
## 6. How to Get retrieval_context (The 2 Strategies)
If you do not have a standard vector database, you cannot extract a native context. We discussed two distinct architectural patterns to solve this:
## Strategy 1: The G-Eval "No-Context" Pattern (Logic Verification)
Instead of fetching source documents, you use G-Eval to skip the context parameter entirely. You supply custom criteria steps telling the judge LLM how to review code logic directly. [23] 



                                                                                                                                     1. Claim Extraction Before Critic ScoringDeepEval Feature: FaithfulnessMetric [26]How it works: This is DeepEval's exact mechanical baseline. When you run a faithfulness check, DeepEval's background judge model does not just guess a score. It first extracts an explicit, bulleted list of individual factual claims from your AI's answer, and then checks each one separately.2. Source-Grounded VerificationDeepEval Feature: retrieval_context mapping [26]How it works: For document-based tasks, DeepEval's FaithfulnessMetric forces every single extracted claim to map back to the exact text snippets provided in your retrieval_context array. If a claim cannot be verified by your source text, it is immediately flagged as unsupported.3. Split the Critic Into Multiple JudgesDeepEval Feature: Multi-metric evaluation arraysHow it works: DeepEval completely avoids "blurry scores" by providing completely isolated, modular classes for each type of judge. You can instantiate separate judges for factuality, instruction-following, safety, and formatting, and run them all together.4. Make Critic Output StricterDeepEval Feature: Rich metric properties (metric.reason and metadata) [26]How it works: Instead of a simple pass/fail, DeepEval's metrics populate verbose reason strings. For example, the FaithfulnessMetric populates an evaluation breakdown that clearly shows exactly which claims were unsupported or contradicted.5. Do Not Skip Critic for Simple/Casual TasksDeepEval Feature: Global programmatic middleware integrationHow it works: Because DeepEval runs inside standard Python backend scripts, you can hook it into your central API routing logic. This ensures every single user query passes through the evaluation check, preventing casual prompts from sneaking past quality controls.6. Add "I Don't Know" EnforcementDeepEval Feature: Custom GEval criteriaHow it works: You can use DeepEval's G-Eval feature to create a metric specifically designed to enforce honesty. You pass a custom rule stating: "If the input question cannot be answered by the provided context, the model must output 'I don't know'. Penalize any attempt to guess or hallucinate details." [26]7. Use Deterministic Validators Where PossibleDeepEval Feature: Native pytest integration and JSON schemasHow it works: For strict rule verification (like JSON validation, matching exact code strings, or tracking quote spans), DeepEval allows you to run classic python code or regex checks side-by-side with your LLM tests. DeepEval also has built-in parameters to enforce strict JSON structure outputs.Code Example: Implementing Upgrades #3 and #4Here is a Python example showing how to split the critic into multiple specialized judges (Upgrade #3) and capture their strict, individual reasons (Upgrade #4):pythonfrom deepeval.test_case import LLMTestCase
from deepeval.metrics import FaithfulnessMetric, AnswerRelevanceMetric, ToxicityMetric

# 1. Setup the data container
test_case = LLMTestCase(
    input="Give me the revenue numbers for Q3.",
    actual_output="Our Q3 revenue was $14 million dollars, you idiot.",
    retrieval_context=["Q3 financial statements indicate total revenue reached $14.2 million."]
)

# 2. Split the critic into 3 separate, specialized judges (Upgrade #3)
fact_judge = FaithfulnessMetric(threshold=0.8)
relevance_judge = AnswerRelevanceMetric(threshold=0.8)
safety_judge = ToxicityMetric(threshold=0.5)

# 3. Run all evaluations
fact_judge.measure(test_case)
relevance_judge.measure(test_case)
safety_judge.measure(test_case)

# 4. Get strict, separate feedback for each area (Upgrade #4)
print(f"Factuality Score: {fact_judge.score} | Reason: {fact_judge.reason}\n")
print(f"Relevance Score: {relevance_judge.score} | Reason: {relevance_judge.reason}\n")
print(f"Safety Score: {safety_judge.score} | Reason: {safety_judge.reason}\n")
Use code with caution.If you ran this code, the Factuality judge would give a high score, the Relevance judge would pass, but the Safety judge would fail because of the phrase "you idiot". Because you split them up, you know exactly what to fix!Would you like help writing out the custom G-Eval rules to enforce the "I don't know" requirement (Upgrade #6) for your application?11 sitesAI and Testing: Faithfulness – Stories from a Software Tester11 Feb 2026 — In the previous post we looked at the Answer Relevancy metric with DeepEval and got some intuitions in place about how to start th...testerstories.comDeepEval by Confident AI - The LLM Evaluation Framework30 May 2026 — Choose and Run Metrics deepeval offers many more multi-turn metrics beyond those listed above, including GoalAccuracyMetric , Topi...DeepEvalAnswer Relevancydeepeval 's answer relevancy metric is a self-explaining LLM-Eval, meaning it outputs a reason for its metric score.DeepEvalShow allYou said: Do we need to use any official api of deepeval to use or is it a normal packageYou do not need to buy or use any official API key or commercial platform from DeepEval to use it.DeepEval is a standard, completely open-source Python package that you install via pip.Where DeepEval Gets its Power (The LLM Requirement)Because DeepEval uses an "LLM-As-A-Judge" workflow, it does need some LLM to run the background math and text analysis. You have two choices for how to provide this:Option 1: Use your own OpenAI/Anthropic API Key (Most Popular)DeepEval will use its built-in prompts and send them to OpenAI or Anthropic using your own personal developer keys. DeepEval doesn't charge you anything; you only pay standard, tiny fractions of a cent per test directly to OpenAI.pythonimport os
# DeepEval automatically detects this and uses it to run the tests
os.environ["OPENAI_API_KEY"] = "your-personal-openai-key"
Use code with caution.Option 2: Run it 100% Free Locally (Using Ollama / Llama 3)If you want to run evaluations completely free with zero APIs or cloud dependencies, you can configure DeepEval to use a free local model running on your laptop through tools like Ollama.pythonfrom deepeval.models.base_model import DeepEvalBaseLLM
from langchain_community.llms import Ollama

# Tell DeepEval to use a free, local model as the judge instead of OpenAI
class LocalOllamaJudge(DeepEvalBaseLLM):
    def __init__(self):
        self.model = Ollama(model="llama3")
    def load_model(self):
        return self.model
    def generate(self, prompt: str) -> str:
        return self.model.invoke(prompt)

local_judge = LocalOllamaJudge()
# Pass 'local_judge' directly into any DeepEval metric!
Use code with caution.What is the "Official" DeepEval Platform then?DeepEval's parent company runs a cloud dashboard platform called Confident AI.It is completely optional.If you run deepeval login in your terminal, it connects your code to their website so you can see pretty graphs of your test scores over time.If you do not want it, you simply ignore it. The Python package remains 100% free and functional locally on your machine.







           I have an existing enterprise FastAPI multi-agent code automation system called Autocoder. It currently uses all-MiniLM-L6-v2 (sentence-transformers) for intent classification with cosine similarity and a manual orchestration pipeline in orchestrator.py. I want to replace the classification and orchestration with LangGraph (not LlamaIndex — LangGraph is better suited since this is a stateful multi-agent system, not a RAG pipeline).
Current architecture:

app/agents/intent_classifier.py — uses SentenceTransformer("all-MiniLM-L6-v2") to classify into 7 intents: general_chat, generation, debugging, refactoring, explanation, metadata_extraction, field_extraction
app/agents/orchestrator.py — manually routes to agents, runs validation loop with retries, handles field extraction pipeline separately
app/agents/agents.py — 6 specialist agents + ValidationAgent + FieldExtractionAgent, all inherit from BaseAgent, each has .execute() method
app/core/llm_registry.py — calls GPU server via requests.post(url, data=payload) with fields prompt, model, max_new_token, temperature, department, env. Three models: qwen-text, llama-text, gemma-text via separate HTTPS URLs from env vars

What I want:
Replace the manual orchestration with a LangGraph StateGraph where:

Keep all-MiniLM-L6-v2 as a fast CPU pre-filter that gives an intent hint (don't remove it — it's free and fast)
Add a LangGraph Router node that uses llama-text (via existing llm_registry) to make final routing decisions, can override the allMiniLM hint if context suggests otherwise, and handles multi-step requests like "fix and explain this code"
Each existing agent becomes a LangGraph node — zero changes to agent logic itself
Validation retry loop becomes a LangGraph cycle edge — ValidationAgent PASS → END, ValidationAgent FAIL + attempts < max → Router, ValidationAgent FAIL + attempts >= max → END
Field extraction pipeline stays as a subgraph
LangGraph State should carry: prompt, file_content, file_name, template_content, template_name, intent_hint, current_intent, result, attempts, validation_score, history, session_id, steps

Constraints:

Do NOT change app/agents/agents.py — agents must remain as-is
Do NOT change app/core/llm_registry.py — GPU calls stay the same
Do NOT change app/schemas/models.py — response schema stays the same
The final output must still return a CodeResponse pydantic object
orchestrator.py should call graph.invoke() and map result to CodeResponse
Add a new file app/agents/graph.py for the StateGraph definition
Add langgraph to requirements.txt
LangGraph Router prompt should be sent to llama-text model via existing registry
If LLM router call fails, fall back to allMiniLM classification silently
Temperature for router node: 0.0 (deterministic routing decisions)

Files to create/change:

app/agents/graph.py — NEW, full StateGraph
app/agents/orchestrator.py — replace pipeline with graph.invoke()
app/agents/intent_classifier.py — keep but expose as hint provider only
requirements.txt — add langgraph>=0.2.0

Give me the complete updated code for all changed files.

    Can use this if wanted:
    Great idea. Let me think through this strategically before touching code.

---

## What you're asking

Replace the current 2-step process:
```
1. allMiniLM classifies intent → picks agent
2. Agent runs → validates → done
```

With an **autonomous decision loop**:
```
LangGraph/LlamaIndex router decides which agent to call
→ agent runs
→ router evaluates result
→ decides next step (validate? retry? different agent? done?)
→ no hardcoded routing logic needed
```

---

## LangGraph vs LlamaIndex for this

**LangGraph:**
- Designed exactly for this — stateful multi-agent graphs
- You define nodes (agents) and edges (conditions)
- Has built-in cycles — so "validate → fail → regenerate → validate again" is a native loop
- Works with any LLM, not just OpenAI
- **Best fit for your architecture** since you already have distinct agent roles

**LlamaIndex:**
- Better for RAG (retrieval + generation over documents)
- Has agent routing but it's more document-query focused
- Would make sense for the field extraction part specifically
- Not ideal as the main orchestrator

**Recommendation: LangGraph for orchestration, keep allMiniLM as a fast pre-filter**

---

## Proposed Architecture

```
User Request
     ↓
allMiniLM (CPU, 10ms)        ← keep this — it's fast and free
→ rough intent hint           (generation/debugging/refactoring/etc)
     ↓
LangGraph StateGraph
  ┌─────────────────────────────────────────────────┐
  │  State: {prompt, file, intent_hint, result,     │
  │          attempts, validation_score, history}   │
  │                                                 │
  │  Node: Router                                   │
  │  → reads state + intent_hint                    │
  │  → decides which agent node to call next        │
  │  → can override allMiniLM if context suggests   │
  │                                                 │
  │  Node: CodeGenerationAgent                      │
  │  Node: DebuggingAgent                           │
  │  Node: RefactorAgent                            │
  │  Node: ExplanationAgent                         │
  │  Node: FieldExtractionAgent                     │
  │  Node: ValidationAgent                          │
  │                                                 │
  │  Edge: after agent runs → always go to Validator│
  │  Edge: Validator PASS → END                     │
  │  Edge: Validator FAIL + attempts < max → Router │
  │  Edge: Validator FAIL + attempts >= max → END   │
  │                                                 │
  │  Node: END → return final CodeResponse          │
  └─────────────────────────────────────────────────┘
```

---

## What this replaces vs what stays

| Current | With LangGraph |
|---|---|
| `classifier.classify()` → hardcoded intent→agent map | `Router node` decides dynamically based on full context |
| `orchestrator.py` giant if/else pipeline | LangGraph StateGraph handles flow |
| Validation retry loop (manual for loop) | LangGraph cycle edge handles retries natively |
| Intent classifier still used | Yes — as a fast hint, Router can override |
| All agents unchanged | Yes — just wrapped as LangGraph nodes |
| Field extraction pipeline | Stays as-is, becomes a subgraph |

---

## The key benefit you get

**Right now** — if someone says "fix and also explain this code", it picks ONE intent and misses the other.

**With LangGraph** — Router can say:
```
1. Run DebuggingAgent → fix the code
2. Then run ExplanationAgent → explain the fix
3. Validate both
4. Return combined result
```

Multi-step, multi-agent, automated — no hardcoded logic.

---

## What needs to change

| File | Change |
|---|---|
| `app/agents/graph.py` | **NEW** — LangGraph StateGraph definition |
| `app/agents/orchestrator.py` | Replace pipeline with `graph.invoke()` |
| `app/agents/intent_classifier.py` | Keep as hint provider only |
| `app/agents/agents.py` | Zero changes — agents become graph nodes |
| `requirements.txt` | Add `langgraph` |

---

## Before I implement — two questions:

1. **Your GPU server** — the LangGraph Router node needs to call an LLM to make routing decisions. Should it use one of your existing 3 models (`llama-3-70b` recommended for reasoning) or do you want the routing to stay CPU-only using allMiniLM?

2. **How autonomous** do you want it? Options:
   - **Semi-autonomous** — allMiniLM gives intent, LangGraph handles the retry/validation cycle only
   - **Fully autonomous** — LangGraph Router uses LLM to decide everything including which agent, when to retry, when to switch agents
