"generation": [
    "write a Python function that does this",
    "generate code for a REST API",
    "create a new class to handle this",
    "build a script that automates this task",
    "implement this feature from scratch",
    "write a program that solves this problem",
    "code a utility function for this",
    "develop a module that handles this",
    "write code that performs a specific task",
    "create a program to process some data",
    "build something new that handles this requirement",
    "I need a function that takes input and returns output",
    "produce a working solution for this use case",
    "write a small script to accomplish this goal",
    # ── Web / Frontend ────────────────────────────────────────────
    "write css code for a webpage",
    "write the best css for frontend",
    "generate html and css for a landing page",
    "create a javascript function for the frontend",
    "write css styles for a responsive layout",
    "build a frontend component",
    "generate a stylesheet for this design",
    "write html css javascript code",
    "create a react component",
    "write frontend code for this feature",
    # ── SQL / Other languages ─────────────────────────────────────
    "write a sql query to fetch data",
    "generate a bash script",
    "write a shell script that does this",
    "create a dockerfile for this project",
    "write a yaml configuration file",
],
