INTENT_DEFINITIONS: dict[str, list[str]] = {
    "general_chat": [
        "hi there",
        "hello how are you",
        "thanks for your help",
        "what can you do",
        "good morning",
    ],
    "generation": [
        # Abstract: covers ANY language/framework via semantic interpolation
        "write code to implement this feature",
        "generate a working solution for this task",
        "create a new implementation from scratch",
        "build something that does this",
        "produce code that solves this problem",
        "write the best possible code for this",
        "implement this in any programming language",
        "develop a complete working solution",
        "write code using any technology or framework",
        "generate frontend backend database or scripting code",
    ],
    "debugging": [
        "find and fix the bug in this code",
        "this code throws an error please fix it",
        "something is wrong with my implementation",
        "debug and correct this broken code",
        "my program crashes please help fix it",
    ],
    "refactoring": [
        "improve the quality of this existing code",
        "restructure this code without changing what it does",
        "clean up and optimise this implementation",
        "make this code follow best practices",
        "rewrite this to be more maintainable",
    ],
    "explanation": [
        "explain what this code does",
        "help me understand how this works",
        "describe the logic behind this implementation",
        "what is this code doing and why",
        "walk me through this step by step",
    ],
    "metadata_extraction": [
        "list all dependencies and imports in this project",
        "extract the structure and metadata from this code",
        "what libraries and packages does this use",
        "analyse the project structure and dependencies",
        "find all exported functions classes and modules",
    ],
}
